# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQTT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTT
	
	pod 'CocoaMQTT'

  target 'MQTTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MQTTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
